### ISSUE TITLE
same as() twig function breaks the string discovery in file

### ISSUE THREAD

**Issue by Levdbas** [timber/wp-i18n-twig#5]
Hi @nlemoine 

I was missing a text string in my po file and found out that using [same as](https://twig.symfony.com/doc/3.x/tests/sameas.html) prevented wp-i18n-twig from discovering the strings in files where it is used.

Example piece of code that breaks discovery:

```twig
{% set string = __('Read %s', 'wp-lemon')|format(post.title) %}
{% if complete_random_var is same as(true) %}
    {% set complete_random_var = 'what?' %}
{% endif %}

{# or behind, does not matter #}
{% set string = __('Read %s', 'wp-lemon')|format(post.title) %}
```

Edit: used the debug mode:

`Could not parse file resources/views/components/cards/crd-default.twig: Unexpected token "name" of value "as" ("end of statement block" expected) at line 8. (4.716s)`

**Comment by nlemoine** [comment]
Hi @Levdbas! 

Thanks for your detailed report :)

This is now fixed on the main branch. I have to release the new version but the doc on custom token parsers is still missing. Will do that next week.

**Comment by Levdbas** [comment]
Legend!
